apiVersion: v1
kind: ConfigMap
metadata:
  name: otusapp-config
data:  
  DB_HOST: {{ include "postgresql.fullname" . }}  
  DB_PORT: "{{ printf .Values.postgresql.service.port }}"
  DB_NAME: {{ printf .Values.postgresql.postgresqlDatabase  }}
  DB_USER: {{ printf .Values.postgresql.postgresqlUsername }}  
  ASPNETCORE_ENVIRONMENT: {{ printf .Values.environment.name }}