apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
        - name: "{{ .Chart.Name }}-migrations"
          image: "{{ .Values.image.repository }}-migrations:{{.Values.image.migrationTag}}"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: otusapp-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: otusapp-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: otusapp-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: otusapp-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otusapp-secret
                  key: DB_PASSWORD
      restartPolicy: Never